name: release

on:
  push:
    branches:
      - release/major
      - release/minor
      - release/patch

jobs:
  # test:
  # uses: Dai7Igarashi/graphql_eslint_sample/.github/workflows/test.yml@main

  release:
    name: release github packages
    # needs: test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      packages: write
      contents: write
      pull-requests: write
    env:
      GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      NPM_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com
      - name: Set git config
        run: |
          git config --global user.email "40178733+Dai7Igarashi@users.noreply.github.com[bot]@users.noreply.github.com"
          git config --global user.name "40178733+Dai7Igarashi@users.noreply.github.com[bot]"
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            **/package-lock.json
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}-v1
      - name: Extract branch from git ref
        # name = release / version = major, minor, patch
        run: |
          echo "name=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
          echo "version=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: Install
        run: npm ci
      - name: Build
        run: npx lerna run build
      - name: Versioning, Tagging and Create CHANGELOG
        run: npx lerna version ${{ steps.extract_branch.outputs.version }} --yes
      - name: publish
        run: npx lerna publish from-package --yes
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "chore(release): publish"
          body: "This is an auto-generated PR."
          base: "main"
